import type { Metadata } from "next";
import "./../globals.css";
import Footer from "../components/layout/Footer";
import HeaderWrapper from "../components/layout/HeaderWrapper";


export const metadata: Metadata = {
  title: "Ali Olad Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <HeaderWrapper/> 
        {children}
        <Footer />
      </body>
    </html>
  );
}
